# action.yml
name: 'Docker Test'
description: 'Test using Docker with github actions'

outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
