# Basic workflow to build all components using docker

name: BUILD
description: 'Build all components with docker.'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Workflow
jobs:
  # main build job
  build:
    # The type of runner that the job will run on
    runs:
    using: 'docker'
    image: 'Dockerfile'
    #args:
