# Basic workflow to build all components using docker

name: BUILD
description: 'Build all components with docker.'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Workflow
jobs:
  # main build job
  build:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        d: hello
        uses: ./action
